workflows:
  build-android:
    name: Build Android APK
    environment:
      flutter: stable
    scripts:
      - name: Build signed Android APK
        script: |
          flutter build apk --release \
            --dart-define=KEYSTORE_PATH=${ANDROID_KEYSTORE} \
            --dart-define=KEY_ALIAS=${ANDROID_KEY_ALIAS}

    artifacts:
      - build//outputs//*.apk
